/*
 * LoginFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gem.java.chat;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.swing.JDialog;

/**
 *
 * @author  __USER__
 */
public class LoginFrame extends javax.swing.JFrame {

	/** Creates new form LoginFrame */
	public LoginFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtLoginId = new javax.swing.JTextField();
		txtPwd = new javax.swing.JPasswordField();
		btnLogin = new javax.swing.JButton();
		btnRegist = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u804a\u5929\u5ba4\u767b\u5f55\u7a97\u53e3");

		jLabel1.setText("\u8d26\u53f7\uff1a");

		jLabel2.setText("\u5bc6\u7801\uff1a");

		btnLogin.setText("\u767b\u5f55");
		btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnLoginMouseClicked(evt);
			}
		});

		btnRegist.setText("\u6ce8\u518c");
		btnRegist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnRegistMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		btnLogin)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnRegist))
												.addComponent(
														txtLoginId,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														157,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtPwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														155,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(24, 24, 24)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtLoginId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txtPwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(8, 8, 8)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnRegist)
												.addComponent(btnLogin))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnRegistMouseClicked(java.awt.event.MouseEvent evt) {
		RegistFrame registFrame = new RegistFrame();
		registFrame.setVisible(true);
		this.setVisible(false);//设置事件，单击之后显示注册窗口，隐藏登录窗口
	}

	private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {
		
		String loginId = this.txtLoginId.getText() ;
		String pwd = new String(this.txtPwd.getPassword());
		login(loginId , pwd ) ;//获取输出的账号和密码
	}
	
	private void login(String loginId , String pwd ){
		try {
			Socket socket = new Socket(ServerUtil.IP , ServerUtil.PORT);//创建一个接口，通过点直接获取IP和端口号
			PrintWriter pw = new PrintWriter(socket.getOutputStream());
			StringBuilder strBuilder = new StringBuilder("operate:login");
			strBuilder.append("___")
					.append("loginId:").append(loginId)
					.append("___")
					.append("pwd:").append(pwd);//将账号和密码通过___拼接
			pw.println(strBuilder.toString());
			pw.flush();
			
			InputStream is = socket.getInputStream();
			BufferedReader br = new BufferedReader(new InputStreamReader(is));
			String loginResultMsg = br.readLine();
			if(loginResultMsg!=null && !"".equals(loginResultMsg)){
				
				String[] loginResultMsgArr = loginResultMsg.split("___");
				String loginResultStr = loginResultMsgArr[0];
				String[] loginResultStrArr = loginResultStr.split(":");
				if("loginResult".equals(loginResultStrArr[1]) && "success".equals(loginResultStrArr[2])){
					String personStr =  loginResultMsgArr[1];
					String[] personAttrArr = personStr.split(":::");
					String nickName = personAttrArr[2];//将服务器返回的信息拆分
					
					ChatFrame cf = new ChatFrame(socket,nickName);
					cf.setTitle("欢迎"+nickName +"进入聊天室!");
					cf.setVisible(true);
					this.setVisible(false);
				}else{
					
				}
			}
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnLogin;
	private javax.swing.JButton btnRegist;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtLoginId;
	private javax.swing.JPasswordField txtPwd;
	// End of variables declaration//GEN-END:variables

}