/*
 * RegistFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gem.java.chat;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

/**
 *
 * @author  __USER__
 */
public class RegistFrame extends javax.swing.JFrame {

	/** Creates new form RegistFrame */
	public RegistFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtLoginID = new javax.swing.JTextField();
		txtPwd = new javax.swing.JTextField();
		txtNickName = new javax.swing.JTextField();
		btnregist = new javax.swing.JButton();
		exit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel1.setText("\u8d26\u53f7");

		jLabel2.setText("\u5bc6\u7801");

		jLabel3.setText("\u6635\u79f0");

		txtPwd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtPwdActionPerformed(evt);
			}
		});

		txtNickName.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				txtNickNameMouseClicked(evt);
			}
		});
		txtNickName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtNickNameActionPerformed(evt);
			}
		});

		btnregist.setText("\u6ce8\u518c");
		btnregist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnregistMouseClicked(evt);
			}
		});

		exit.setText("\u9000\u51fa");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(196, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addGap(56, 56, 56)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				btnregist)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				exit))
														.addComponent(
																txtNickName)
														.addComponent(txtPwd)
														.addComponent(
																txtLoginID,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																221,
																Short.MAX_VALUE))
										.addContainerGap(148, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txtLoginID,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(42,
																				42,
																				42)
																		.addComponent(
																				txtPwd,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(61,
																				61,
																				61))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel2)
																		.addGap(51,
																				51,
																				51)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																txtNickName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3)))
										.addGap(36, 36, 36)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(exit)
														.addComponent(btnregist))
										.addContainerGap(46, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void txtNickNameMouseClicked(java.awt.event.MouseEvent evt) {

	}

	private void btnregistMouseClicked(java.awt.event.MouseEvent evt) {
		//获取账号，密码，昵称
		String loginId=txtLoginID.getText();
		String pwd=txtPwd.getText();
		String nickName=txtNickName.getText();
		
		boolean flag=regist(loginId,pwd,nickName);
		if(flag){
			LoginFrame lf=new LoginFrame();
			this.setVisible(false);
			lf.setVisible(true);//如果注册成功隐藏注册界面，显示登录界面
		}else{
			System.out.println("注册失败!");//否则在控制台打印注册失败
		}
	}
	
	private boolean regist(String loginId,String pwd,String nickName){
		try {
			Socket socket=new Socket(ServerUtil.IP,ServerUtil.PORT);
			OutputStream os=socket.getOutputStream();
			PrintWriter pw=new PrintWriter(os);//建立一个输出流 把结果输出给服务器
			
			StringBuilder strBuilder=new StringBuilder("operate:regist");//创建一个拼接的字符串,用operaet:regist代表整条字符串
			strBuilder.append("___")
			.append("loginId:").append(loginId)
			.append("___")
			.append("pwd:").append(pwd)
			.append("___")
			.append("nickName:").append(nickName);
			String msg=strBuilder.toString();
			pw.println(msg);
			pw.flush();//把拼接的字符串用tostring封装成一条String类型的msg然后发送出去
			
			InputStream is=socket.getInputStream();
			BufferedReader br=new BufferedReader(new InputStreamReader(is));//建立一个输入流，接收服务器返回的信息
			String registResultMsg=br.readLine();
			String[]registResultMsgArr=registResultMsg.split(":");//把消息用：作为分割符，
			if("registResult".equals(registResultMsgArr[1])&&"success".equals(registResultMsgArr[2])){
				return true;//如果服务器返回的第二条信息为registResult,第三条信息为success,这说明注册成功
			}else{
				return false;
			}
		
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return false;
	}
	private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtNickNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnregist;
	private javax.swing.JButton exit;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField txtLoginID;
	private javax.swing.JTextField txtNickName;
	private javax.swing.JTextField txtPwd;
	// End of variables declaration//GEN-END:variables

}